'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.3603
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da wsdl, versione=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Web.Services.WebServiceBindingAttribute(Name:="WebServiceSoap", [Namespace]:="http://tempuri.org/")>
Partial Public Class WebService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

    Private MakePageOperationCompleted As System.Threading.SendOrPostCallback

    Private send_email_xmlOperationCompleted As System.Threading.SendOrPostCallback

    Private salva_file_srv_remotoOperationCompleted As System.Threading.SendOrPostCallback

    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://mailsoap.powerapp.it/WebService.asmx"
    End Sub

    '''<remarks/>
    Public Event MakePageCompleted As MakePageCompletedEventHandler

    '''<remarks/>
    Public Event send_email_xmlCompleted As send_email_xmlCompletedEventHandler

    '''<remarks/>
    Public Event salva_file_srv_remotoCompleted As salva_file_srv_remotoCompletedEventHandler

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MakePage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
    Public Function MakePage(ByVal txtSubject As String, ByVal txtBody As String) As String
        Dim results() As Object = Me.Invoke("MakePage", New Object() {txtSubject, txtBody})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function BeginMakePage(ByVal txtSubject As String, ByVal txtBody As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("MakePage", New Object() {txtSubject, txtBody}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function EndMakePage(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub MakePageAsync(ByVal txtSubject As String, ByVal txtBody As String)
        Me.MakePageAsync(txtSubject, txtBody, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub MakePageAsync(ByVal txtSubject As String, ByVal txtBody As String, ByVal userState As Object)
        If (Me.MakePageOperationCompleted Is Nothing) Then
            Me.MakePageOperationCompleted = AddressOf Me.OnMakePageOperationCompleted
        End If
        Me.InvokeAsync("MakePage", New Object() {txtSubject, txtBody}, Me.MakePageOperationCompleted, userState)
    End Sub

    Private Sub OnMakePageOperationCompleted(ByVal arg As Object)
        If (Not (Me.MakePageCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent MakePageCompleted(Me, New MakePageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_email_xml", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
    Public Function send_email_xml(ByVal str_from As String, ByVal str_to As String, ByVal str_subject As String, ByVal str_body As String, ByVal parametri_opzionali As String) As Object
        Dim results() As Object = Me.Invoke("send_email_xml", New Object() {str_from, str_to, str_subject, str_body, parametri_opzionali})
        Return CType(results(0), Object)
    End Function

    '''<remarks/>
    Public Function Beginsend_email_xml(ByVal str_from As String, ByVal str_to As String, ByVal str_subject As String, ByVal str_body As String, ByVal parametri_opzionali As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("send_email_xml", New Object() {str_from, str_to, str_subject, str_body, parametri_opzionali}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function Endsend_email_xml(ByVal asyncResult As System.IAsyncResult) As Object
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), Object)
    End Function

    '''<remarks/>
    Public Overloads Sub send_email_xmlAsync(ByVal str_from As String, ByVal str_to As String, ByVal str_subject As String, ByVal str_body As String, ByVal parametri_opzionali As String)
        Me.send_email_xmlAsync(str_from, str_to, str_subject, str_body, parametri_opzionali, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub send_email_xmlAsync(ByVal str_from As String, ByVal str_to As String, ByVal str_subject As String, ByVal str_body As String, ByVal parametri_opzionali As String, ByVal userState As Object)
        If (Me.send_email_xmlOperationCompleted Is Nothing) Then
            Me.send_email_xmlOperationCompleted = AddressOf Me.Onsend_email_xmlOperationCompleted
        End If
        Me.InvokeAsync("send_email_xml", New Object() {str_from, str_to, str_subject, str_body, parametri_opzionali}, Me.send_email_xmlOperationCompleted, userState)
    End Sub

    Private Sub Onsend_email_xmlOperationCompleted(ByVal arg As Object)
        If (Not (Me.send_email_xmlCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent send_email_xmlCompleted(Me, New send_email_xmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salva_file_srv_remoto", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>
    Public Sub salva_file_srv_remoto(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal file_array() As Byte, ByVal nome As String)
        Me.Invoke("salva_file_srv_remoto", New Object() {file_array, nome})
    End Sub

    '''<remarks/>
    Public Function Beginsalva_file_srv_remoto(ByVal file_array() As Byte, ByVal nome As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("salva_file_srv_remoto", New Object() {file_array, nome}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Sub Endsalva_file_srv_remoto(ByVal asyncResult As System.IAsyncResult)
        Me.EndInvoke(asyncResult)
    End Sub

    '''<remarks/>
    Public Overloads Sub salva_file_srv_remotoAsync(ByVal file_array() As Byte, ByVal nome As String)
        Me.salva_file_srv_remotoAsync(file_array, nome, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub salva_file_srv_remotoAsync(ByVal file_array() As Byte, ByVal nome As String, ByVal userState As Object)
        If (Me.salva_file_srv_remotoOperationCompleted Is Nothing) Then
            Me.salva_file_srv_remotoOperationCompleted = AddressOf Me.Onsalva_file_srv_remotoOperationCompleted
        End If
        Me.InvokeAsync("salva_file_srv_remoto", New Object() {file_array, nome}, Me.salva_file_srv_remotoOperationCompleted, userState)
    End Sub

    Private Sub Onsalva_file_srv_remotoOperationCompleted(ByVal arg As Object)
        If (Not (Me.salva_file_srv_remotoCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent salva_file_srv_remotoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>
Public Delegate Sub MakePageCompletedEventHandler(ByVal sender As Object, ByVal e As MakePageCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code")>
Partial Public Class MakePageCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs

    Private results() As Object

    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub

    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary()
            Return CType(Me.results(0), String)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>
Public Delegate Sub send_email_xmlCompletedEventHandler(ByVal sender As Object, ByVal e As send_email_xmlCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code")>
Partial Public Class send_email_xmlCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs

    Private results() As Object

    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub

    '''<remarks/>
    Public ReadOnly Property Result() As Object
        Get
            Me.RaiseExceptionIfNecessary()
            Return CType(Me.results(0), Object)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>
Public Delegate Sub salva_file_srv_remotoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
